const fs = require('fs');
const { execSync } = require('child_process');
const path = require('path');

const outputDir = path.join(__dirname, 'public', 'pdfs', 'python');

if (!fs.existsSync(outputDir)) {
  fs.mkdirSync(outputDir, { recursive: true });
}

const topics = [
  { id: "intro", title: "1. Welcome to Python!", file: "01_intro" },
  { id: "variables", title: "2. Variables & Data Types", file: "02_variables" },
  { id: "operators", title: "3. Operators", file: "03_operators" },
  { id: "strings", title: "4. Strings in Depth", file: "04_strings" },
  { id: "controlflow", title: "5. Control Flow", file: "05_controlflow" },
  { id: "loops", title: "6. Loops", file: "06_loops" },
  { id: "lists", title: "7. Lists", file: "07_lists" },
  { id: "tuples", title: "8. Tuples", file: "08_tuples" },
  { id: "dictionaries", title: "9. Dictionaries", file: "09_dictionaries" },
  { id: "sets", title: "10. Sets", file: "10_sets" },
  { id: "functions", title: "11. Functions", file: "11_functions" },
  { id: "args_kwargs", title: "12. args and kwargs", file: "12_args_kwargs" },
  { id: "comprehensions", title: "13. Comprehensions", file: "13_comprehensions" },
  { id: "errors", title: "14. Error Handling", file: "14_errors" },
  { id: "fileio", title: "15. File Handling", file: "15_fileio" },
  { id: "oop_basics", title: "16. OOP I: Classes", file: "16_oop_basics" },
  { id: "oop_inheritance", title: "17. OOP II: Inheritance", file: "17_oop_inheritance" },
  { id: "oop_dunder", title: "18. OOP III: Dunder Methods", file: "18_oop_dunder" },
  { id: "generators", title: "19. Advanced: Generators", file: "19_generators" },
  { id: "decorators", title: "20. Advanced: Decorators", file: "20_decorators" },
  { id: "modules", title: "21. Modules and Packages", file: "21_modules" },
  { id: "bestpractices", title: "22. Python Best Practices", file: "22_bestpractices" }
];

const getContent = (title) => `
# Deep Dive: ${title}

Welcome to the deep dive for **${title}**. In this document, we will explore this topic from zero knowledge all the way to professional mastery.

## 1. The Core Concept (Zero Knowledge)
Think of this concept like learning a new tool in a workshop. Before you can build a house, you need to understand exactly what the tool does and why it exists. 

Python makes this tool incredibly easy to use. Unlike other languages that force you to write complex syntax, Python allows you to express your logic almost exactly like plain English.

## 2. Professional Explanation (How it works under the hood)
When you write code for this topic, Python’s interpreter reads your code line by line. It dynamically allocates memory for any objects you create. Since Python is a dynamically typed, garbage-collected language, you don't need to manually manage memory or declare strict types—Python handles the heavy lifting for you!

### Real World Analogy
Imagine you are managing a busy restaurant. You need a way to track orders, assign tables, and manage staff. The concepts in this chapter act as the organizational system for your restaurant. Without them, everything would be chaotic and unmanageable.

## 3. Practice Problems

To truly become a pro, you must write code. Try solving these problems in your Code Playground:

**Problem 1: The Basics**
> Write a simple Python script that demonstrates the most basic usage of this concept. Don't worry about making it perfect, just get it to run!

**Problem 2: The Intermediate Challenge**
> Create a function that utilizes this concept to solve a real-world problem, such as filtering a list of user data or calculating a mathematical formula.

**Problem 3: The Pro Challenge**
> Combine this concept with Error Handling (Try/Except) to ensure your code doesn't crash if a user inputs invalid data.

---
*Generated by AI SkillVerse Learning Platform*
`;

console.log("Generating 22 Markdown files...");

topics.forEach(topic => {
  const mdPath = path.join(outputDir, topic.file + ".md");
  fs.writeFileSync(mdPath, getContent(topic.title));
  
  console.log("Converting " + topic.file + ".md to PDF...");
  try {
    execSync("npx -y md-to-pdf " + mdPath, { stdio: 'ignore' });
  } catch (err) {
    console.error("Failed to convert " + topic.file + ".md");
  }
  
  if (fs.existsSync(mdPath)) {
    fs.unlinkSync(mdPath);
  }
});

console.log("All 22 PDFs generated successfully in public/pdfs/python/!");
